<?php

namespace App;

use Caffeinated\Shinobi\Concerns\HasRolesAndPermissions;
use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable, HasRolesAndPermissions;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    /**
     * Get the area that owns the user.
     */
    public function area() {
        return $this->belongsTo('App\Area');
    }

    /**
     * Get the area managed by this user.
     */
    public function managed_area() {
        return $this->hasOne('App\Area');
    }

    /**
     * Get the solicitudes made by this user
     */
    public function solicitudes() {
        return $this->hasMany('App\SolicitudPermiso');
    }

    /**
     * Get the notifications generated by this user
     */
    public function notificaciones() {
        return $this->hasMany('App\Notificacion');
    }
    
}
